"""Whitespace-only input must never become an empty persisted string.

`Field(min_length=1)` does not protect a string field on its own. Pydantic
checks `min_length` *before* an `after`-mode `field_validator` runs, so `"   "`
satisfies the length check and is then trimmed to `""` by the strip validator.
The column is `NOT NULL`, not non-empty, so the empty string reaches the database
and is only findable by querying for it.

Two tests guard this:

- `test_required_string_field_rejects_whitespace_only` — an explicit table over
  every known affected field, so a failure names the field that regressed.
- `test_no_request_model_required_string_field_accepts_whitespace_only` — the
  structural invariant. It walks every request-shaped schema, so a *new* schema
  that wires a required field to the permissive helper fails here without anyone
  remembering to add a row to the table above.

Response models (`*Read`, `*Response`, and anything with
`model_config.from_attributes`) are excluded from the invariant: they are
validated from an already-persisted row rather than from client input, so a blank
value cannot reach them through the API. Adding a validator there would not
prevent a bad write, it would only turn a corrupt row into a 500 on read.
"""

import enum
from datetime import UTC, date, datetime
from uuid import uuid4

import pytest
from pydantic import BaseModel, ValidationError

from app.schemas.auth import RegisterRequest
from app.schemas.bed import BedCreate
from app.schemas.building import BuildingCreate
from app.schemas.floor import FloorCreate
from app.schemas.onboarding import OnboardingRequest
from app.schemas.organization import OrganizationCreate
from app.schemas.property import PropertyCreate
from app.schemas.resident_profile import ResidentProfileCreate
from app.schemas.room import RoomCreate
from app.schemas.user import UserCreate
from app.schemas.validation import strip_optional, strip_text

BLANK_VALUES = ["   ", "\t\n", " "]

# Fields whose generated sample would fail their own validator, so the sample has
# to be spelled out. Everything else is generated by `_sample`.
_LITERALS = {
    "slug": "abc-pg",
    "organization_slug": "abc-pg",
    "password": "Passw0rd!",
    "phone": "9876543210",
}

# (id, model, required string field under test)
REQUIRED_STRING_FIELDS = [
    ("UserCreate.full_name", UserCreate, "full_name"),
    ("OrganizationCreate.name", OrganizationCreate, "name"),
    ("PropertyCreate.name", PropertyCreate, "name"),
    ("BuildingCreate.name", BuildingCreate, "name"),
    ("FloorCreate.name", FloorCreate, "name"),
    ("RoomCreate.room_number", RoomCreate, "room_number"),
    ("BedCreate.bed_number", BedCreate, "bed_number"),
    (
        "ResidentProfileCreate.emergency_contact_name",
        ResidentProfileCreate,
        "emergency_contact_name",
    ),
    (
        "ResidentProfileCreate.emergency_contact_phone",
        ResidentProfileCreate,
        "emergency_contact_phone",
    ),
    ("ResidentProfileCreate.address", ResidentProfileCreate, "address"),
    ("OnboardingRequest.organization_name", OnboardingRequest, "organization_name"),
    ("RegisterRequest.full_name", RegisterRequest, "full_name"),
    ("RegisterRequest.phone", RegisterRequest, "phone"),
]

_IDS = [case[0] for case in REQUIRED_STRING_FIELDS]


def _sample(f) -> object | None:
    """A valid value for one field, or `None` when the annotation is not understood."""
    annotation = f.annotation
    if isinstance(annotation, type) and issubclass(annotation, enum.Enum):
        return list(annotation)[0]
    if "EmailStr" in str(annotation):
        return "a@example.com"
    if annotation is str:
        return "value"
    text = str(annotation)
    for needle, value in (
        ("datetime", datetime(2026, 1, 1, tzinfo=UTC)),
        ("date", date(2026, 1, 1)),
        ("UUID", uuid4()),
        ("bool", True),
        ("int", 1),
        ("float", 1.0),
        ("dict", {}),
        ("list", []),
    ):
        if needle in text:
            return value
    return None


def _valid_kwargs(model: type[BaseModel]) -> dict[str, object]:
    """Valid values for every required field, so a failure isolates the field under
    test rather than a missing sibling."""
    kwargs: dict[str, object] = {}
    for name, f in model.model_fields.items():
        if not f.is_required():
            continue
        value = _LITERALS.get(name, _sample(f))
        assert value is not None, f"no sample for {model.__name__}.{name}"
        kwargs[name] = value
    return kwargs


@pytest.mark.parametrize("blank", BLANK_VALUES)
@pytest.mark.parametrize(
    ("label", "model", "field"), REQUIRED_STRING_FIELDS, ids=_IDS
)
def test_required_string_field_rejects_whitespace_only(
    label: str, model: type[BaseModel], field: str, blank: str
) -> None:
    kwargs = {**_valid_kwargs(model), field: blank}
    with pytest.raises(ValidationError):
        model(**kwargs)


@pytest.mark.parametrize(
    ("label", "model", "field"), REQUIRED_STRING_FIELDS, ids=_IDS
)
def test_required_string_field_still_accepts_real_values(
    label: str, model: type[BaseModel], field: str
) -> None:
    """The guard must reject only whitespace, not padded or genuine values."""
    instance = model(**{**_valid_kwargs(model), field: "  Sunrise Boys PG  "})
    assert getattr(instance, field) == "Sunrise Boys PG"


def _schema_models() -> set[type[BaseModel]]:
    """Every model declared in `app.schemas`, and nothing else.

    `BaseModel.__subclasses__()` reaches every Pydantic model in the process,
    including the OpenAPI schemas FastAPI imports, so results are filtered to our
    own package.
    """
    import importlib
    import pkgutil

    import app.schemas as schemas_pkg

    for module in pkgutil.iter_modules(schemas_pkg.__path__):
        importlib.import_module(f"app.schemas.{module.name}")

    found: set[type[BaseModel]] = set()
    stack = list(BaseModel.__subclasses__())
    while stack:
        current = stack.pop()
        if current in found:
            continue
        found.add(current)
        stack.extend(current.__subclasses__())
    return {m for m in found if m.__module__.startswith("app.schemas")}


# The request surface, by the naming convention every module here already follows.
# Anything else (`*Read`, `*Response`, or a bare `*Base`) is only ever validated
# from data the backend produced, so a blank value cannot reach it via the API.
_REQUEST_SUFFIXES = ("Create", "Update", "Request")


def _is_request_model(model: type[BaseModel]) -> bool:
    if model.model_config.get("from_attributes"):
        return False
    return model.__name__.endswith(_REQUEST_SUFFIXES)


def test_no_request_model_required_string_field_accepts_whitespace_only() -> None:
    """The structural invariant: no required plain-`str` field on a request-shaped
    schema may accept whitespace-only input.

    `EmailStr` is exempt by construction (Pydantic rejects a blank email), and so
    is any `str`-derived enum or annotated alias, because only a bare `str`
    annotation is selected here.
    """
    offenders: list[str] = []
    unbuildable: list[str] = []
    checked = 0

    for model in sorted(_schema_models(), key=lambda m: m.__name__):
        if not _is_request_model(model):
            continue

        required = {
            name: f for name, f in model.model_fields.items() if f.is_required()
        }
        targets = [name for name, f in required.items() if f.annotation is str]
        if not targets:
            continue

        base: dict[str, object] = {}
        for name, f in required.items():
            value = _LITERALS.get(name, _sample(f))
            if value is None:
                base = {}
                break
            base[name] = value
        if not base:
            unbuildable.append(f"{model.__name__} (no sample for a required field)")
            continue

        try:
            model(**base)
        except ValidationError as exc:
            unbuildable.append(f"{model.__name__} (baseline invalid: {exc.error_count()})")
            continue

        for name in targets:
            checked += 1
            for blank in BLANK_VALUES:
                try:
                    instance = model(**{**base, name: blank})
                except ValidationError:
                    continue
                offenders.append(
                    f"{model.__name__}.{name} accepted {blank!r} "
                    f"-> {getattr(instance, name, None)!r}"
                )
                break

    assert not offenders, (
        "required string fields accepting whitespace-only:\n" + "\n".join(offenders)
    )
    # Surfaced rather than silently swallowed: a model we cannot build is a field
    # this invariant is not currently covering.
    assert not unbuildable, (
        "models skipped by the invariant (add a sample so they are covered):\n"
        + "\n".join(unbuildable)
    )
    assert checked >= len(REQUIRED_STRING_FIELDS)


def test_strip_text_rejects_blank_and_keeps_none() -> None:
    assert strip_text(None) is None
    assert strip_text("  x  ") == "x"
    for blank in BLANK_VALUES:
        with pytest.raises(ValueError, match="must not be blank"):
            strip_text(blank)


def test_strip_optional_allows_blank_and_none() -> None:
    assert strip_optional(None) is None
    assert strip_optional("  x  ") == "x"
    for blank in BLANK_VALUES:
        assert strip_optional(blank) == ""
    assert strip_optional("") == ""
