"""create buildings, floors, rooms and beds

Revision ID: 2c6024f973d8
Revises: b34eed04c876
Create Date: 2026-09-20 18:18:47.230758

"""
# ruff: noqa: E501, I001, UP007, UP035  (autogenerated by Alembic)
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c6024f973d8'
down_revision: Union[str, Sequence[str], None] = 'b34eed04c876'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildings',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_buildings_organization_id_organizations')),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_buildings_property_id_properties')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_buildings')),
    sa.UniqueConstraint('property_id', 'name', name=op.f('uq_buildings_property_id'))
    )
    op.create_index(op.f('ix_buildings_organization_id'), 'buildings', ['organization_id'], unique=False)
    op.create_index(op.f('ix_buildings_property_id'), 'buildings', ['property_id'], unique=False)
    op.create_table('floors',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('building_id', sa.Uuid(), nullable=False),
    sa.Column('floor_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], name=op.f('fk_floors_building_id_buildings')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_floors_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_floors')),
    sa.UniqueConstraint('building_id', 'floor_number', name=op.f('uq_floors_building_id'))
    )
    op.create_index(op.f('ix_floors_building_id'), 'floors', ['building_id'], unique=False)
    op.create_index(op.f('ix_floors_organization_id'), 'floors', ['organization_id'], unique=False)
    op.create_table('rooms',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('floor_id', sa.Uuid(), nullable=False),
    sa.Column('room_number', sa.String(length=50), nullable=False),
    sa.Column('room_type', sa.Enum('SINGLE', 'DOUBLE', 'TRIPLE', 'FOUR_SHARE', 'FIVE_SHARE', 'CUSTOM', name='room_type'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], name=op.f('fk_rooms_floor_id_floors')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_rooms_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rooms')),
    sa.UniqueConstraint('floor_id', 'room_number', name=op.f('uq_rooms_floor_id'))
    )
    op.create_index(op.f('ix_rooms_floor_id'), 'rooms', ['floor_id'], unique=False)
    op.create_index(op.f('ix_rooms_organization_id'), 'rooms', ['organization_id'], unique=False)
    op.create_index(op.f('ix_rooms_room_number'), 'rooms', ['room_number'], unique=False)
    op.create_table('beds',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('bed_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'OCCUPIED', 'BLOCKED', 'MAINTENANCE', name='bed_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_beds_organization_id_organizations')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_beds_room_id_rooms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_beds')),
    sa.UniqueConstraint('room_id', 'bed_number', name=op.f('uq_beds_room_id'))
    )
    op.create_index(op.f('ix_beds_organization_id'), 'beds', ['organization_id'], unique=False)
    op.create_index(op.f('ix_beds_room_id'), 'beds', ['room_id'], unique=False)
    op.create_index(op.f('ix_beds_status'), 'beds', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_beds_status'), table_name='beds')
    op.drop_index(op.f('ix_beds_room_id'), table_name='beds')
    op.drop_index(op.f('ix_beds_organization_id'), table_name='beds')
    op.drop_table('beds')
    op.drop_index(op.f('ix_rooms_room_number'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_organization_id'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_floor_id'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_floors_organization_id'), table_name='floors')
    op.drop_index(op.f('ix_floors_building_id'), table_name='floors')
    op.drop_table('floors')
    op.drop_index(op.f('ix_buildings_property_id'), table_name='buildings')
    op.drop_index(op.f('ix_buildings_organization_id'), table_name='buildings')
    op.drop_table('buildings')
    # ### end Alembic commands ###
