"""create resident profiles table

Revision ID: 44df52db429b
Revises: 2c6024f973d8
Create Date: 2026-09-20 18:53:51.136196

"""
# ruff: noqa: E501, I001, UP007, UP035  (autogenerated by Alembic)
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44df52db429b'
down_revision: Union[str, Sequence[str], None] = '2c6024f973d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resident_profiles',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('organization_member_id', sa.Uuid(), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=255), nullable=False),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_resident_profiles_organization_id_organizations')),
    sa.ForeignKeyConstraint(['organization_member_id'], ['organization_members.id'], name=op.f('fk_resident_profiles_organization_member_id_organization_members')),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_resident_profiles_property_id_properties')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resident_profiles')),
    sa.UniqueConstraint('organization_member_id', name=op.f('uq_resident_profiles_organization_member_id'))
    )
    op.create_index(op.f('ix_resident_profiles_organization_id'), 'resident_profiles', ['organization_id'], unique=False)
    op.create_index(op.f('ix_resident_profiles_property_id'), 'resident_profiles', ['property_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resident_profiles_property_id'), table_name='resident_profiles')
    op.drop_index(op.f('ix_resident_profiles_organization_id'), table_name='resident_profiles')
    op.drop_table('resident_profiles')
    # ### end Alembic commands ###
