"""create tenant stays table

Revision ID: ba2e89791bd7
Revises: 44df52db429b
Create Date: 2026-09-20 19:20:45.397027

"""
# ruff: noqa: E501, I001, UP007, UP035  (autogenerated by Alembic)
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba2e89791bd7'
down_revision: Union[str, Sequence[str], None] = '44df52db429b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_stays',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('resident_profile_id', sa.Uuid(), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('bed_id', sa.Uuid(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'CANCELLED', name='tenant_stay_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['bed_id'], ['beds.id'], name=op.f('fk_tenant_stays_bed_id_beds')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_tenant_stays_organization_id_organizations')),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_tenant_stays_property_id_properties')),
    sa.ForeignKeyConstraint(['resident_profile_id'], ['resident_profiles.id'], name=op.f('fk_tenant_stays_resident_profile_id_resident_profiles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_stays'))
    )
    op.create_index(op.f('ix_tenant_stays_bed_id'), 'tenant_stays', ['bed_id'], unique=False)
    op.create_index(op.f('ix_tenant_stays_organization_id'), 'tenant_stays', ['organization_id'], unique=False)
    op.create_index(op.f('ix_tenant_stays_resident_profile_id'), 'tenant_stays', ['resident_profile_id'], unique=False)
    op.create_index('uq_tenant_stays_active_bed', 'tenant_stays', ['bed_id'], unique=True, sqlite_where=sa.text("status = 'ACTIVE'"), postgresql_where=sa.text("status = 'ACTIVE'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_tenant_stays_active_bed', table_name='tenant_stays', sqlite_where=sa.text("status = 'ACTIVE'"), postgresql_where=sa.text("status = 'ACTIVE'"))
    op.drop_index(op.f('ix_tenant_stays_resident_profile_id'), table_name='tenant_stays')
    op.drop_index(op.f('ix_tenant_stays_organization_id'), table_name='tenant_stays')
    op.drop_index(op.f('ix_tenant_stays_bed_id'), table_name='tenant_stays')
    op.drop_table('tenant_stays')
    # ### end Alembic commands ###
