"""create complaints table

Revision ID: d20aa62f77e7
Revises: ba2e89791bd7
Create Date: 2026-09-26 14:19:30.513319

"""
# ruff: noqa: E501, I001, UP007, UP035  (autogenerated by Alembic)
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd20aa62f77e7'
down_revision: Union[str, Sequence[str], None] = 'ba2e89791bd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaints',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('resident_profile_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('MAINTENANCE', 'ELECTRICAL', 'PLUMBING', 'FOOD', 'HOUSEKEEPING', 'SECURITY', 'INTERNET', 'OTHER', name='complaint_category'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='complaint_priority'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'ON_HOLD', 'RESOLVED', 'CLOSED', name='complaint_status'), nullable=False),
    sa.Column('assigned_to_member_id', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_member_id'], ['organization_members.id'], name=op.f('fk_complaints_assigned_to_member_id_organization_members')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_complaints_organization_id_organizations')),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_complaints_property_id_properties')),
    sa.ForeignKeyConstraint(['resident_profile_id'], ['resident_profiles.id'], name=op.f('fk_complaints_resident_profile_id_resident_profiles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_complaints'))
    )
    op.create_index(op.f('ix_complaints_organization_id'), 'complaints', ['organization_id'], unique=False)
    op.create_index(op.f('ix_complaints_priority'), 'complaints', ['priority'], unique=False)
    op.create_index(op.f('ix_complaints_property_id'), 'complaints', ['property_id'], unique=False)
    op.create_index(op.f('ix_complaints_resident_profile_id'), 'complaints', ['resident_profile_id'], unique=False)
    op.create_index(op.f('ix_complaints_status'), 'complaints', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_complaints_status'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_resident_profile_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_property_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_priority'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_organization_id'), table_name='complaints')
    op.drop_table('complaints')
    # ### end Alembic commands ###
