"""create complaint comments table

Revision ID: e820ed82dda3
Revises: d20aa62f77e7
Create Date: 2026-09-26 14:48:52.072320

"""
# ruff: noqa: E501, I001, UP007, UP035  (autogenerated by Alembic)
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e820ed82dda3'
down_revision: Union[str, Sequence[str], None] = 'd20aa62f77e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaint_comments',
    sa.Column('complaint_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], name=op.f('fk_complaint_comments_complaint_id_complaints')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_complaint_comments_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_complaint_comments'))
    )
    op.create_index(op.f('ix_complaint_comments_complaint_id'), 'complaint_comments', ['complaint_id'], unique=False)
    op.create_index(op.f('ix_complaint_comments_user_id'), 'complaint_comments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_complaint_comments_user_id'), table_name='complaint_comments')
    op.drop_index(op.f('ix_complaint_comments_complaint_id'), table_name='complaint_comments')
    op.drop_table('complaint_comments')
    # ### end Alembic commands ###
